### PR TITLE
Fix ticket not reassigned

### LINKED ISSUE #140: Ticket isn't reassigned to the person who start the work on it
When a ticket is assigned to person A but the person B move it to in progress, the ticket isn't being automatically assigned to the person B.

This issue is causing some problems because a lot of stories appear to be done by someone who isn't working on them

### PR DESCRIPTION
**Pull request by iagodahlem**
- fixes #140

cm42-central-fix-assign

### CODE REVIEW

File: app/assets/javascripts/views/form_view.js [hunk 1]
```diff
@@ -116,13 +116,14 @@ module.exports = Backbone.View.extend({
     return el;
   },
 
-  bindElementToAttribute: function(el, name, eventType) {
+  bindElementToAttribute: function(el, name, eventType, silent = true) {
     var that = this;
     eventType = typeof(eventType) != 'undefined' ? eventType : "change";
     $(el).on(eventType, function() {
+      console.log('silent', silent)
```
Comment (matheusazzi) [inline app/assets/javascripts/views/form_view.js]: ✂️

File: spec/javascripts/models/story_spec.js [hunk 2]
```diff
@@ -474,4 +474,16 @@ describe('Story', function() {
...
   });
 
+  describe('changeState', function() {
+    it('set the owner to the current user when is started', function() {
+      this.story.set({ onwed_by_id: 123 });
+      this.story.changeState(this.story, 'started');
+      expect(this.story.get('owned_by_id')).toBe(999);
+    });
+
+    it('dont change the owner when state is not started', function() {
```
Comment (matheusazzi) [inline spec/javascripts/models/story_spec.js]: @iagodahlem Did you mean "when **story** is not started" ?

File: app/assets/javascripts/views/form_view.js (hunk 1 above)
Comment (iagodahlem) [inline app/assets/javascripts/views/form_view.js]: Cutted. :smile:

File: spec/javascripts/models/story_spec.js [hunk 3]
```diff
@@ -474,4 +474,16 @@ describe('Story', function() {
...
   });
 
+  describe('changeState', function() {
+    it('set the owner to the current user when is started', function() {
+      this.story.set({ onwed_by_id: 123 });
+      this.story.changeState(this.story, 'started');
+      expect(this.story.get('owned_by_id')).toBe(999);
+    });
+
+    it('dont change the owner when story is not started', function() {
```
Comment (marclerodrigues) [inline spec/javascripts/models/story_spec.js]: `it('does not change the...')`

File: spec/javascripts/models/story_spec.js [hunk 4]
```diff
@@ -474,4 +474,16 @@ describe('Story', function() {
     });
   });
 
+  describe('changeState', function() {
+    it('set the owner to the current user when is started', function() {
```
Comment (marclerodrigues) [inline spec/javascripts/models/story_spec.js]: `it('sets the owner to the current user when story is started', ...)`

Comment (iagodahlem) [inline spec/javascripts/models/story_spec.js]: :+1:

File: spec/javascripts/models/story_spec.js (hunk 3 above)
Comment (iagodahlem) [inline spec/javascripts/models/story_spec.js]: :+1:

File: CHANGELOG.md [hunk 5]
```diff
@@ -13,6 +13,7 @@
 
 ### Fixed
 - Story History bug when story actions where triggered
+- Ticket not being reassignedt to current user when state change to "started"
```
Comment (iagodahlem) [inline CHANGELOG.md]: :+1:

**Comment by marclerodrigues** [comment]
Also take a look at: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History. The session about Squashing Commits.

File: app/assets/javascripts/models/story.js [hunk 6]
```diff
@@ -39,7 +39,7 @@ var Story = module.exports = Backbone.Model.extend({
   },
 
   changeState: function(model, new_value) {
-    if (new_value == "started" && !this.get('owned_by_id')) {
+    if (new_value == "started") {
```
Comment (talyssonoc) [inline app/assets/javascripts/models/story.js]: Can we rename `new_value` to `newValue`? I know you weren't the one that added the whole function but it seems short enough to be easy to rename it and enforce the code styling we're using. Also, it's better to use `===` instead of `==`.

File: app/assets/javascripts/views/form_view.js [hunk 7]
```diff
@@ -116,13 +116,13 @@ module.exports = Backbone.View.extend({
     return el;
   },
 
-  bindElementToAttribute: function(el, name, eventType) {
+  bindElementToAttribute: function(el, name, eventType, silent = true) {
```
Comment (talyssonoc) [inline app/assets/javascripts/views/form_view.js]: What do you think about adding a options object instead of a new parameter? That way we avoid to adding a new parameter every time we need a new option here.

You can do something like:

```js
bindElementToAttribute: function(el, name, eventType, { silent = true } = {}) {
 // ...
```

File: app/assets/javascripts/views/form_view.js [hunk 8]
```diff
@@ -116,13 +116,13 @@ module.exports = Backbone.View.extend({
...
     var that = this;
     eventType = typeof(eventType) != 'undefined' ? eventType : "change";
     $(el).on(eventType, function() {
       var obj = {};
       obj[name] = $(el).val();
-      that.model.set(obj, {silent: true});
+      that.model.set(obj, {silent: silent});
```
Comment (talyssonoc) [inline app/assets/javascripts/views/form_view.js]: Since the name of the variable is already `silent`, you can pass just: `that.model.set(obj, { silent });` and it'll convert it internally to `{ silent: silent }`

File: app/assets/javascripts/views/story_view.js [hunk 9]
```diff
@@ -377,7 +377,6 @@ module.exports = FormView.extend({
 
           const $storyState = $('<div class="form-group" data-story-state></div>');
           $(div).append($storyState);
-
```
Comment (talyssonoc) [inline app/assets/javascripts/views/story_view.js]: I think we don't need this change in this PR.

File: spec/javascripts/models/story_spec.js [hunk 10]
```diff
@@ -474,4 +474,16 @@ describe('Story', function() {
     });
   });
 
+  describe('changeState', function() {
+    it('sets the owner to the current user when story is started', function() {
```
Comment (talyssonoc) [inline spec/javascripts/models/story_spec.js]: It'll be better to add contexts here, like:

```js
context('when story is started', function() {
  it('sets the owner to the current user', function() { ... });
});

context('when story is not started', function() {
  it('does not change the owner', function() { ... });
});
```

File: spec/javascripts/models/story_spec.js [hunk 11]
```diff
@@ -474,4 +474,16 @@ describe('Story', function() {
...
+      this.story.set({ onwed_by_id: 123 });
+      this.story.changeState(this.story, 'started');
+      expect(this.story.get('owned_by_id')).toBe(999);
```
Comment (talyssonoc) [inline spec/javascripts/models/story_spec.js]: Where does the `999` come from?

File: app/assets/javascripts/models/story.js (hunk 6 above)
Comment (iagodahlem) [inline app/assets/javascripts/models/story.js]: Sure, I just tried to change less things as possible.

File: app/assets/javascripts/views/form_view.js (hunk 7 above)
Comment (iagodahlem) [inline app/assets/javascripts/views/form_view.js]: Yeah, that's looks good.

File: app/assets/javascripts/views/story_view.js (hunk 9 above)
Comment (iagodahlem) [inline app/assets/javascripts/views/story_view.js]: Probably, this was a trailing space that was removed when I saved this file with editorconfig on my editor.

File: spec/javascripts/models/story_spec.js (hunk 10 above)
Comment (iagodahlem) [inline spec/javascripts/models/story_spec.js]: Ok, that's look better, I will add it.

File: app/assets/javascripts/views/story_view.js (hunk 9 above)
Comment (talyssonoc) [inline app/assets/javascripts/views/story_view.js]: It's ok then!

File: spec/javascripts/models/story_spec.js (hunk 11 above)
Comment (iagodahlem) [inline spec/javascripts/models/story_spec.js]: At the beginning of the file has [these mocks](https://github.com/iagodahlem/cm42-central/blob/b50f30544663a36871d1a6dcae8f90798af39794/spec/javascripts/models/story_spec.js#L10).
